name: anaKrys
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.0
  - jupyterlab
  - numpy
  - pandas
  - uproot>=3.0,<4.0
  - matplotlib
  - scipy
  - tqdm
  - pip
  - pip:
    - succolib
